package task4.testproduction.java;
import java.util.*;
public enum Token {
    THROW, EPS, SINGLEQUOTE, STATIC, INTERFACE, AND_ASSIGN, SEMICOLON, BREAK, BYTE, ELSE, NONZERODIGIT, IF, ENUM, SUB, BANG, LPAREN, DOT, CASE, AT, ELLIPSIS, LBRACK, PUBLIC, THROWS, LBRACE, GOTO, SUB_ASSIGN, SEMI, CHAR, ASSIGN, SPACE, IMPORT, CATCH, MUL_ASSIGN, DOUBLE, PROTECTED, LONG, COMMA, PRIVATE, CONTINUE, DIV, STRING, LE, VOLATILE, EXTENDS, INSTANCEOF, NEW, ADD, ZERO, LT, CLASS, FINALLY, CONST, PACKAGE, OR_ASSIGN, TRY, SYNCHRONIZED, NULL, MUL, FOR, TRUE, FINAL, RPAREN, CARET, BOOLEAN, NOTEQUAL, RBRACK, RBRACE, AND, THIS, SWITCH, VOID, TRANSIENT, FLOAT, NATIVE, DIV_ASSIGN, ABSTRACT, STRICTFP, INT, QUESTION, DOUBLEQUOTE, RETURN, ADD_ASSIGN, EOF, GE, SUPER, OR, MOD, XOR_ASSIGN, ASSERT, EQUAL, IMPLEMENTS, COLON, GT, DIGIT, SHORT, MOD_ASSIGN, WHILE, TILDE, FALSE, DEFAULT, NONDIGITIDSYMBOL
}
